using System.Collections;
using System.Collections.Generic;
using UnityEngine;

#pragma warning disable 0649

public class EnemyMoveRandomlyAroundPointState : FSMState<Enemy>
{
    [SerializeField] private float patrolRadius = 8f;
    [SerializeField] private float spottingPlayerDistance = 40f;
    [SerializeField] private float newSteeringForce = 50f;
    [SerializeField] private float minDistanceFromAreaBorder = 4f;
    [SerializeField] private Transform point;

    private ParticleManager particleManager;
    private ShootingController shootingController;
    private SteeringManager steering;

    public override void Enter()
    {
        base.Enter();

        CheckPoint();

        GetComponent<Shooting>().enabled = false;

        particleManager = agent.particleManager;
        shootingController = agent.shootingController;
        steering = agent.steering;

        steering.SetMaxSteeringForce(newSteeringForce);
        particleManager.SwitchWandering();
    }

    private void FixedUpdate()
    {
        SteerToStayInArea();
        steering.Wander();

        steering.AvoidObstacles();
        steering.FlockingSeparation(Enemy.allAsSteerables);

        steering.LookWhereGoing();

        CheckDetectPlayer();
    }

    public override void Exit()
    {
        base.Exit();
        GetComponent<RegisterCombat>().detectedPlayer = true;
        GetComponent<Shooting>().enabled = true;
        steering.SetMaxSteeringForce(steering.GetInitalSteeringForce());
        particleManager.DisableAllParticleGroups();
    }

    private void SteerToStayInArea()
    {
        Vector3 toCenter = point.position - transform.position;
        float distance = toCenter.magnitude;
        if (distance >= patrolRadius - minDistanceFromAreaBorder)
        {
            steering.Seek(point.position);
        }
    }

    private void CheckDetectPlayer()
    {
        float distance = (Player.Instance.transform.position - transform.position).magnitude;
        if (distance <= spottingPlayerDistance && shootingController.CanShootAt(Player.Instance.gameObject))
        {
            Debug.Log("Detected the player, distance: " + distance);

            agent.audio.PlayOnDetectedPlayer();
            agent.fsm.ChangeState<EnemyStateFollowPlayer>();
        }
    }

    private void CheckPoint()
    {
        if (point != null) return;
        var go = new GameObject("AutogeneratedPatrolPoint_" + name);
        point = go.transform;
        point.position = transform.position;
    }
}
